#!/bin/sh

set -ue
umask 0022
export LC_ALL=C
export UNIX_STD=2003 # to make HP-UX conform to POSIX
[ "${ZSH_VERSION:-}" ] && setopt shwordsplit interactivecomments

dirname="$(cd -- "$(dirname -- "$0")" && pwd)" || exit $?
DIR="${dirname%/}/"
echo $DIR

echo $0 "@" $(pwd)
echo "========="
$DIR/src/test_sub $DIR $1
