#!/bin/sh

set -eu
umask 0022
export LC_ALL=C
export UNIX_STD=2003
[ "${ZSH_VERSION:-}" ] && setopt shwordsplit interactivecomments

# The entire contents of GitHub repository are stored in the linked directory.
# So, let's get the full PATH to the linked directory

CMD_LINK=$(ls -l "$0" | awk '{print $NF}')

DIR="$(cd -- "$(dirname -- "$0")" && pwd)" || exit $?
DIR="${DIR%/}/"
DIR=$(
  cd "$DIR" || exit $?
  cd "${CMD_LINK%/*}/" || exit $?
  pwd
)

# Then, you can execute commands
"$DIR"/src/test_sub $DIR ${1:-Brew}

Rscript "$DIR"/src/test_R
